name: Assign Reviewers
on:
  pull_request:
    types:
      - opened

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            # const { data: members } = await github.teams.listMembersInOrg({
            #   org: 'your-organization-name',
            #   team_slug: 'your-team-name'
            # });

            # const reviewers = members.map(member => member.login);
            const teams = await github.teams
            echo teams
            await github.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers
            });
