name: Update PR Description
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PR Description
        run: |
          BRANCH_NAME=$(jq -r '.pull_request.head.ref' "${GITHUB_EVENT_PATH}")
          echo "Branch name is $BRANCH_NAME"
          DESCRIPTION=$(jq -n --arg branch "$BRANCH_NAME" '{"body": "This PR is for branch: \($branch)"}')
          jq -n "$DESCRIPTION" > pr_description.json
          jq -c '. + {"body": (.body | rtrimstr("\n"))}' pr_description.json > new_description.json
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d @new_description.json "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}"
      
